name: Deploy to Railway

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
      
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'  # or whichever version you're using
      
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
      
    - name: Use Node 16
      uses: actions/setup-node@v2
      with:
        node-version: '16.x'
      
    - name: Install Railway CLI
      run: npm i -g @railway/cli

    - name: Deploy to Railway
      run: railway up --service ${{ secrets.RAILWAY_SERVICE }}
      env:
        RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
