name: Deploy to Railway

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
      
    - name: Use Node 16
      uses: actions/setup-node@v2
      with:
        node-version: '16.x'
      
    - name: Install Railway CLI
      run: npm i -g @railway/cli

    - name: Deploy to Railway
      run: railway up --service ${{ secrets.RAILWAY_PROJECT_ID }}
      env:
        RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}